# networks:
#   monitoring:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 10.0.0.0/24
          # gateway: 172.18.0.1

networks:
  monitor_monitoring:
    external: true

services:
  # dns:
  #   image: jpillora/dnsmasq
  #   container_name: dns
  #   ports:
  #     - "53:53/udp"
  #     - "53:53/tcp"
  #     # - "8053:8053"  # Web UI for managing DNS
  #   # environment:
  #   #   - HTTP_USER=admin
  #   #   - HTTP_PASS=admin  # Change this in production
  #   volumes:
  #     - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
  #     - ./dnsmasq/hosts:/etc/hosts
  #   cap_add:
  #     - NET_ADMIN
  #   networks:
  #     monitor_monitoring:
  #       ipv4_address: 192.168.2.53
  #   restart: unless-stopped

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./nginx:/config/nginx
      - ./nginx/logs:/var/log/nginx
      # - ./nginx/etc/resolv.conf:/etc/resolv.conf
    networks:
      - monitor_monitoring
        # ipv4_address: 192.168.2.100
    environment:
      - TZ=UTC
      # - DOCKER_MODS=linuxserver/mods:nginx-proxy-confs
    # depends_on:
    #   - dns
    # dns:
    #   - 10.0.0.53
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    volumes:
      - './authelia:/config'
      # - ./authelia/secrets:/config/secrets
    environment:
      - TZ=UTCw
      - X_AUTHELIA_CONFIG_FILTERS=template
      - DOMAIN=${DOMAIN}
      - LLDAP_LDAP_BASE_DN=${LLDAP_LDAP_BASE_DN}
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/config/secrets/AUTHENTICATION_BACKEND_LDAP_PASSWORD
      - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/SESSION_SECRET
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secrets/STORAGE_ENCRYPTION_KEY
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/config/secrets/identity_providers/oidc/HMAC_SECRET
      - AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE=/config/secrets/identity_validation/RESET_PASSWORD_JWT_SECRET
    networks:
      - monitor_monitoring
    ports:
      - 9091:9091
    restart: unless-stopped
    # depends_on:
    #   - redis
    healthcheck:
      disable: true

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - monitor_monitoring
  #   restart: unless-stopped

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   environment:
  #     - GF_SERVER_DOMAIN=smplwise.com
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards
  #   networks:
  #     - monitoring

  # grafana-srv:
  #   image: grafana/grafana-enterprise
  #   container_name: grafana-srv
  #   # restart: unless-stopped
  #   environment:
  #     - GF_SERVER_DOMAIN=smplwise.com
  #   volumes:
  #     - grafana_storage:/var/lib/grafana
  #     - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  #   ports:
  #     - '3000:3000'
  #   networks:
  #     - monitoring
  #   dns:
  #     - 10.0.0.53

  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    networks:
      - monitor_monitoring
    # dns:
    #   - 10.0.0.53
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      # - "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      # - "lldap_data:/data"
      # Alternatively, you can mount a local folder
      - "./lldap/data:/data"
    environment:
      # - UID=####
      # - GID=####
      # - TZ=####/####
      # - LLDAP_VERBOSE=true
      - LLDAP_LDAP_USER_EMAIL=${LLDAP_LDAP_USER_EMAIL}
      - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS}
      - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LLDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=${LLDAP_LDAP_BASE_DN}
      - LLDAP_HTTP_URL=https://${DOMAIN}
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # If using SMTP, set the following variables
      # - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      # - LLDAP_SMTP_OPTIONS__SERVER=smtp.example.com
      # - LLDAP_SMTP_OPTIONS__PORT=465 # Check your smtp providor's documentation for this setting
      # - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      # - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
      # - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
      # - LLDAP_SMTP_OPTIONS__FROM=no-reply <no-reply@example.com> # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
      # - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.

  frontend:
    image: smplwise/smplwise-ui:0.1.0
    container_name: frontend
    # restart: unless-stopped
    # dns:
    #   - 10.0.0.53
    networks:
      - monitor_monitoring
    environment:
      - VITE_APP_URL=https://${DOMAIN}
      - VITE_GRAFANA_URL=https://${DOMAIN}/grafana
      - VITE_GRAFANA_DEFAULT_ORG_ID=1
      - VITE_AUTH_URL=https://${DOMAIN}/auth
      - VITE_AUTH_CLIENT_ID=frontend
      - VITE_AUTH_CLIENT_SECRET=${VITE_AUTH_CLIENT_SECRET}
      - VITE_AUTH_REDIRECT_URI=https://${DOMAIN}/app
    ports:
      - 5173:5173

# volumes:
#   grafana-storage:
