export const oidcConfig = {
    authority: import.meta.env.VITE_AUTH_URL,
    client_id: import.meta.env.VITE_AUTH_CLIENT_ID,
    client_secret: import.meta.env.VITE_AUTH_CLIENT_SECRET,
    redirect_uri: `https://100.85.232.42/callback`,
    scope: "openid profile email groups",
    // client_authentication: "client_secret_post",
    loadUserInfo: true,
    post_logout_redirect_uri: `${import.meta.env.VITE_AUTH_URL}`,
    remove_tokens_on_signout: true,
    omit_scopes_when_requesting: true,
    automaticSilentRenew: true,
    monitorSession: true,
    // silent_redirect_uri: `https://100.85.232.42/silent-callback`,
    silentRequestTimeout: 10000,
};